package com.example.autopayroll_mobile.mainApp

import android.os.Bundle
import android.view.LayoutInflater
import android.view.View
import android.view.ViewGroup
import androidx.compose.ui.platform.ComposeView
import androidx.compose.ui.platform.ViewCompositionStrategy // Import this
import androidx.fragment.app.Fragment
import androidx.fragment.app.activityViewModels
import androidx.navigation.fragment.findNavController
import androidx.navigation.fragment.navArgs
import com.example.autopayroll_mobile.composableUI.announcementUI.AnnouncementDetailScreen
import com.example.autopayroll_mobile.ui.theme.AutoPayrollMobileTheme
import com.example.autopayroll_mobile.viewmodel.AnnouncementViewModel

class AnnouncementDetailHostFragment : Fragment() {

    // Get the shared ViewModel from the Activity scope
    private val announcementViewModel: AnnouncementViewModel by activityViewModels()

    // Get the navigation arguments (this is the 'announcementId' from the XML)
    // The 'AnnouncementDetailHostFragmentArgs' class is auto-generated by the
    // Navigation component (Safe Args) when you build the project.
    private val args: AnnouncementDetailHostFragmentArgs by navArgs()

    override fun onCreateView(
        inflater: LayoutInflater, container: ViewGroup?,
        savedInstanceState: Bundle?
    ): View {
        return ComposeView(requireContext()).apply {
            // ## FIX: Set the composition strategy for proper lifecycle management ##
            setViewCompositionStrategy(ViewCompositionStrategy.DisposeOnViewTreeLifecycleDestroyed)

            layoutParams = ViewGroup.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.MATCH_PARENT
            )

            setContent {
                AutoPayrollMobileTheme {
                    // Pass the NavController, the ID from the arguments,
                    // and the shared ViewModel to your composable screen
                    AnnouncementDetailScreen(
                        navController = findNavController(),
                        announcementId = args.announcementId,
                        viewModel = announcementViewModel
                    )
                }
            }
        }
    }
}